import "@/app/globals.css";
import { Cairo } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Sidebar from "./Sidebar";
import React from "react";
import Header from "@/components/mainparts/Header";
import Wrapper from "./Wrapper";
import styles from "@/app/styles.module.css";
import Footer from "@/components/footer/Footer";

config.autoAddCss = false;
const cairo = Cairo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ar" dir="rtl" className={`antialiased m-0`}>
      <body className={`${cairo.className} min-h-screen`}>
        <Wrapper>
          <Sidebar />
          <div className={`flex flex-col flex-1 ${styles.landingBg} min-w-0`}>
            <Header />
            <div className={`m-0 bg-[var(--secondary)]`}>{children}</div>
          </div>
        </Wrapper>
        <Footer />
      </body>
    </html>
  );
}
