import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Cairo } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Sidebar from "./Sidebar";
import React from "react";
config.autoAddCss = false;

const interF = Inter({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={` ${cairo.className} min-h-full flex w-full`}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
